const BankAccountTypes = {
  GET_BANK_DETAILS_START: "GET_BANK_DETAILS_START",
  GET_BANK_DETAILS_SUCCESS: "GET_BANK_DETAILS_SUCCESS",
  GET_BANK_DETAILS_FAILURE: "GET_BANK_DETAILS_FAILURE",

  BANK_CREATE_START: "BANK_CREATE_START",
  BANK_CREATE_SUCCESS: "BANK_CREATE_SUCCESS",
  BANK_CREATE_FAILURE: "BANK_CREATE_FAILURE",

  BANK_UPDATE_START: "BANK_UPDATE_START",
  BANK_UPDATE_SUCCESS: "BANK_UPDATE_SUCCESS",
  BANK_UPDATE_FAILURE: "BANK_UPDATE_FAILURE",

  GET_ALL_BANKS_START: "GET_ALL_BANKS_START",
  GET_ALL_BANKS_SUCCESS: "GET_ALL_BANKS_SUCCESS",
  GET_ALL_BANKS_FAILURE: "GET_ALL_BANKS_FAILURE",

  CLEAR_BANK_MESSAGES: "CLEAR_BANK_MESSAGES",
};
export default BankAccountTypes;
