const TransactionActionTypes = {
  GET_TRANSACTIONS_START: "GET_TRANSACTIONS_START",
  GET_TRANSACTIONS_SUCCESS: "GET_TRANSACTIONS_SUCCESS",
  GET_TRANSACTIONS_FAILURE: "GET_TRANSACTIONS_FAILURE",

  GET_ALL_TRANSACTIONS_START: "GET_ALL_TRANSACTIONS_START",
  GET_ALL_TRANSACTIONS_SUCCESS: "GET_ALL_TRANSACTIONS_SUCCESS",
  GET_ALL_TRANSACTIONS_FAILURE: "GET_ALL_TRANSACTIONS_FAILURE",

  // DEPOSIT_START: "DEPOSIT_START",
  // DEPOSIT_SUCCESS: "DEPOSIT_SUCCESS",
  // DEPOSIT_FAILURE: "DEPOSIT_FAILURE",
  //
  // WITHDRAW_START: "WITHDRAW_START",
  // WITHDRAW_SUCCESS: "WITHDRAW_SUCCESS",
  // WITHDRAW_FAILURE: "WITHDRAW_FAILURE",
};
export default TransactionActionTypes;
