const BankTypes = {
  GET_BANK_DETAILS_START: "GET_BANK_DETAILS_START",
  GET_BANK_DETAILS_SUCCESS: "GET_BANK_DETAILS_SUCCESS",
  GET_BANK_DETAILS_FAILURE: "GET_BANK_DETAILS_FAILURE",

  BANK_CREATE_START: "BANK_CREATE_START",
  BANK_CREATE_SUCCESS: "BANK_CREATE_SUCCESS",
  BANK_CREATE_FAILURE: "BANK_CREATE_FAILURE",

  BANK_UPDATE_START: "BANK_UPDATE_START",
  BANK_UPDATE_SUCCESS: "BANK_UPDATE_SUCCESS",
  BANK_UPDATE_FAILURE: "BANK_UPDATE_FAILURE",
};
export default BankTypes;
