const ReferralActionTypes = {
  GET_REFERRAL_START: "GET_REFERRAL_START",
  GET_REFERRAL_SUCCESS: "GET_REFERRAL_SUCCESS",
  GET_REFERRAL_FAILURE: "GET_REFERRAL_FAILURE",
};
export default ReferralActionTypes;
