const UsersActionTypes = {
  GET_ALL_USER_DETAILS_START: "GET_ALL_USER_DETAILS_START",
  GET_ALL_USER_DETAILS_SUCCESS: "GET_ALL_USER_DETAILS_SUCCESS",
  GET_ALL_USER_DETAILS_FAILURE: "GET_ALL_USER_DETAILS_FAILURE",

  UPDATE_USER_START: "UPDATE_USER_START",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",
};
export default UsersActionTypes;
